apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "frontend.fullname" . } }
  labels: { { - include "frontend.labels" . | nindent 4 } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels: { { - include "frontend.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels: { { - include "frontend.selectorLabels" . | nindent 8 } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: { { .Values.service.port } }
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_API_URL
              value: { { .Values.env.NEXT_PUBLIC_API_URL | quote } }
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
