apiVersion: v1
kind: Service
metadata:
  name: { { include "postgres.fullname" . } }
  labels: { { - include "postgres.labels" . | nindent 4 } }
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector: { { - include "postgres.selectorLabels" . | nindent 4 } }
