apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: { { include "postgres.fullname" . } }
  labels: { { - include "postgres.labels" . | nindent 4 } }
spec:
  serviceName: { { include "postgres.fullname" . } }
  replicas: 1
  selector:
    matchLabels: { { - include "postgres.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels: { { - include "postgres.selectorLabels" . | nindent 8 } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: { { .Values.auth.username | quote } }
            - name: POSTGRES_PASSWORD
              value: { { .Values.auth.password | quote } }
            - name: POSTGRES_DB
              value: { { .Values.auth.database | quote } }
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: { { .Values.persistence.size | quote } }
